### ISSUE TITLE
Can some one please explain the slugify key

### ISSUE THREAD

**Issue by themestechnology** [shigeya/jekyll-category-archive-plugin#14]
Sorry perhaps I am having a bad day is this a setting in the _config.yml thx

**Comment by shigeya** [comment]
OK. let me close:)

**Comment by themestechnology** [comment]
Well I still do not get there I can stop WORD%20WORD int he URL so its WORD-WORD

**Comment by shigeya** [comment]
@themestechnology The code of the `slugify` (in Jekyll 2.5.3) method substitute all non-alpha-numeric characters into dash, so you can't avoid unless you patch. The current development version may change its behavior but not released yet. (sorry for late reply)
