### ISSUE TITLE
Getting an error when using plugin

### ISSUE THREAD

**Issue by eberkund** [shigeya/jekyll-category-archive-plugin#9]
Hi, when I follow the instructions and copy the 2 files into my Jekyll site I am getting this when I try to generate (using --trace):

`/Users/erik/chessground/_plugins/category_archive_plugin.rb:82:in 'initialize': undefined method '[]' for nil:NilClass (NoMethodError)
	from /Users/erik/chessground/_plugins/category_archive_plugin.rb:32:in 'new'
	from /Users/erik/chessground/_plugins/category_archive_plugin.rb:32:in 'block in generate'
	from /Users/erik/chessground/_plugins/category_archive_plugin.rb:31:in 'each'
	from /Users/erik/chessground/_plugins/category_archive_plugin.rb:31:in 'generate'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/site.rb:280:in 'block in generate'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/site.rb:279:in 'each'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/site.rb:279:in 'generate'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/site.rb:50:in 'process'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/command.rb:28:in 'process_site'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:56:in 'build'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:34:in 'process'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/lib/jekyll/commands/serve.rb:26:in 'block (2 levels) in init_with_program'
	from /Users/erik/.rvm/gems/ruby-head/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'call'
	from /Users/erik/.rvm/gems/ruby-head/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'block in execute'
	from /Users/erik/.rvm/gems/ruby-head/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'each'
	from /Users/erik/.rvm/gems/ruby-head/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'execute'
	from /Users/erik/.rvm/gems/ruby-head/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in 'go'
	from /Users/erik/.rvm/gems/ruby-head/gems/mercenary-0.3.5/lib/mercenary.rb:19:in 'program'
	from /Users/erik/.rvm/gems/ruby-head/gems/jekyll-2.5.2/bin/jekyll:20:in '<top (required)>'
	from /Users/erik/.rvm/gems/ruby-head/bin/jekyll:23:in 'load'
	from /Users/erik/.rvm/gems/ruby-head/bin/jekyll:23:in '<main>'
	from /Users/erik/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in 'eval'
	from /Users/erik/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in '<main>'`

**Comment by breakhearts** [comment]
I meet the same problem, and i use windows version ruby and jekyii, does the platform relate to the problem?

**Comment by eberkund** [comment]
It shouldn't matter that you're using Windows, although the version of Jekyll and Ruby probably makes a difference.

**Comment by breakhearts** [comment]
I found the problem, you must set category_archive in _config.yml, or code in       
<code>
"if site.config['category_archive']['slugify']"
</code>
will crash

**Comment by eberkund** [comment]
@breakhearts, can you elaborate on that?

**Comment by breakhearts** [comment]
when i review the code here <code>Users/erik/chessground/_plugins/category_archive_plugin.rb:82:in 'initialize': undefined method '[]' for nil:NilClass (NoMethodError)</code> , i found the code <code>"if site.config['category_archive']['slugify']" </code> when category_archive not set in _config.yml, <code>site.config['category_archive']</code> is <code>Nil</code>, then <code>"if site.config['category_archive']['slugify']" </code> will report error,  after i set that, this error disappeared, but i fall into another problem, still can not finish build

**Comment by eberkund** [comment]
Ah, I have fixed the issue by adding:

`category_archive:
 path: /`

to my `_config.yml` file. I think that this should be the new default value instead of the "null string" because that does not work and causes the site no to generate.

**Comment by shigeya** [comment]
Ah, I now understand what have happened. One of the pull request I have merged haven't checked existence of category_archive key. try to fix now.

**Comment by shigeya** [comment]
Pushed 18ee57e5eed1a8e78f2a16d94989e748a3dc435b please try if you can... But since the patch has incorporated on Dec 12, it might not fix @eberkund's issue (directly)

**Comment by eberkund** [comment]
Yes, that fixed the issue. It now works without needing anything extra in `_config.yml`

**Comment by shigeya** [comment]
Thank you
